import { Salon, SalonService, Hairstyle, SalonStaff, User, QueueToken, Notification, Appointment } from '../types';

export const DEMO_USER: User = {
  id: 'usr-customer-001',
  name: 'Rahul Sharma',
  email: 'rahul.sharma@example.com',
  phone: '+91 98765 43210',
  role: 'CUSTOMER',
  dob: '1998-05-14',
  gender: 'Male',
  profileImage: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
  createdAt: '2026-09-01T10:00:00Z',
};

export const DEMO_SALON: Salon = {
  id: 'salon-pune-01',
  name: 'SalonFlow Studio & Lounge',
  address: 'Lane 7, Koregaon Park, Pune, Maharashtra 411001',
  area: 'Koregaon Park',
  city: 'Pune',
  phone: '+91 20 2615 4890',
  rating: 4.9,
  reviewCount: 384,
  currentWaitMinutes: 24,
  totalWaiting: 4,
  imageUrl: 'https://images.unsplash.com/photo-1585747860715-2ba37e788b70?auto=format&fit=crop&w=600&q=80',
  openingTime: '09:00 AM',
  closingTime: '09:30 PM',
  status: 'OPEN',
};

export const DEMO_SALONS: Salon[] = [
  DEMO_SALON,
  {
    id: 'salon-pune-02',
    name: 'SalonFlow Elite Barbering',
    address: 'High Street, Baner, Pune, Maharashtra 411045',
    area: 'Baner',
    city: 'Pune',
    phone: '+91 20 2729 1120',
    rating: 4.8,
    reviewCount: 290,
    currentWaitMinutes: 15,
    totalWaiting: 2,
    imageUrl: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&w=600&q=80',
    openingTime: '09:30 AM',
    closingTime: '10:00 PM',
    status: 'OPEN',
  },
  {
    id: 'salon-pune-03',
    name: "SalonFlow Men's Club & Spa",
    address: 'Near Phoenix Marketcity, Viman Nagar, Pune 411014',
    area: 'Viman Nagar',
    city: 'Pune',
    phone: '+91 20 2663 8840',
    rating: 4.9,
    reviewCount: 420,
    currentWaitMinutes: 30,
    totalWaiting: 5,
    imageUrl: 'https://images.unsplash.com/photo-1621605815971-fbc98d665033?auto=format&fit=crop&w=600&q=80',
    openingTime: '08:30 AM',
    closingTime: '09:30 PM',
    status: 'OPEN',
  },
  {
    id: 'salon-pune-04',
    name: 'SalonFlow Precision Grooming',
    address: 'East Avenue, Kalyani Nagar, Pune 411006',
    area: 'Kalyani Nagar',
    city: 'Pune',
    phone: '+91 20 2665 9900',
    rating: 4.7,
    reviewCount: 180,
    currentWaitMinutes: 10,
    totalWaiting: 1,
    imageUrl: 'https://images.unsplash.com/photo-1622286342621-4bd786c2447c?auto=format&fit=crop&w=600&q=80',
    openingTime: '10:00 AM',
    closingTime: '09:00 PM',
    status: 'OPEN',
  },
];

export const DEMO_SERVICES: SalonService[] = [
  {
    id: 'srv-01',
    salonId: 'salon-pune-01',
    name: 'Precision Signature Haircut',
    description: 'Bespoke consultation, precision shear cut, warm rinse, and premium matte styling.',
    price: 499,
    durationMinutes: 30,
    category: 'Haircuts',
    imageUrl: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&w=600&q=80',
    isActive: true,
  },
  {
    id: 'srv-02',
    salonId: 'salon-pune-01',
    name: 'Skin Fade & Textured Crop',
    description: 'Seamless taper or skin fade on the sides with textured scissor cut on top. Styled with clay.',
    price: 599,
    durationMinutes: 35,
    category: 'Haircuts',
    imageUrl: 'https://images.unsplash.com/photo-1622286342621-4bd786c2447c?auto=format&fit=crop&w=600&q=80',
    isActive: true,
  },
  {
    id: 'srv-03',
    salonId: 'salon-pune-01',
    name: 'Royal Beard Sculpt & Hot Towel',
    description: 'Sharp straight-razor contouring, beard softening oil massage, and steaming herbal hot towel.',
    price: 349,
    durationMinutes: 25,
    category: 'Beard & Shave',
    imageUrl: 'https://images.unsplash.com/photo-1621605815971-fbc98d665033?auto=format&fit=crop&w=600&q=80',
    isActive: true,
  },
  {
    id: 'srv-04',
    salonId: 'salon-pune-01',
    name: 'The Executive Combo (Cut + Beard)',
    description: 'Complete grooming package: signature haircut, precision beard shaping, and quick scalp refresh.',
    price: 799,
    durationMinutes: 50,
    category: 'Haircuts',
    imageUrl: 'https://images.unsplash.com/photo-1585747860715-2ba37e788b70?auto=format&fit=crop&w=600&q=80',
    isActive: true,
  },
  {
    id: 'srv-05',
    salonId: 'salon-pune-01',
    name: 'Charcoal Scalp Detox & Head Massage',
    description: 'Invigorating exfoliating scalp scrub followed by relaxing pressure point massage and cooling tonic.',
    price: 649,
    durationMinutes: 30,
    category: 'Spa & Treatments',
    imageUrl: 'https://images.unsplash.com/photo-1519699047748-de8e457a634e?auto=format&fit=crop&w=600&q=80',
    isActive: true,
  },
  {
    id: 'srv-06',
    salonId: 'salon-pune-01',
    name: 'Modern Balayage & Ash Highlights',
    description: 'Subtle dimensional color blending using ammonia-free salon toners with bond-repair mask.',
    price: 1899,
    durationMinutes: 75,
    category: 'Color & Styling',
    imageUrl: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&w=600&q=80',
    isActive: true,
  },
];

export const DEMO_HAIRSTYLES: Hairstyle[] = [
  {
    id: 'HS01',
    name: 'Textured Crop',
    description: 'High fade on the sides with short, choppy layered texture on top. Clean blunt fringe.',
    imageUrl: 'https://images.unsplash.com/photo-1622286342621-4bd786c2447c?auto=format&fit=crop&w=600&q=80',
    category: 'Modern Short',
    suitableFaceShapes: ['Oval', 'Heart', 'Diamond', 'Square'],
    suitableHairTypes: ['Straight', 'Wavy'],
    mappedServiceId: 'srv-02',
  },
  {
    id: 'HS02',
    name: 'Low Drop Fade & Pompadour',
    description: 'Swept back high-volume top balanced with a crisp drop fade around the ears and nape.',
    imageUrl: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&w=600&q=80',
    category: 'Classic Modern',
    suitableFaceShapes: ['Round', 'Square', 'Oval'],
    suitableHairTypes: ['Straight', 'Wavy', 'Thick'],
    mappedServiceId: 'srv-01',
  },
  {
    id: 'HS03',
    name: 'Executive Side Part & Taper',
    description: 'Sleek parted timeless aesthetic with natural graduation around the neckline.',
    imageUrl: 'https://images.unsplash.com/photo-1605497788044-5a32c7078486?auto=format&fit=crop&w=600&q=80',
    category: 'Formal / Classic',
    suitableFaceShapes: ['Square', 'Oval', 'Oblong'],
    suitableHairTypes: ['Straight', 'Fine', 'Medium'],
    mappedServiceId: 'srv-01',
  },
  {
    id: 'HS04',
    name: 'Modern Textured Quiff',
    description: 'Brushed up forward quiff with matte clay finish and subtle low taper.',
    imageUrl: 'https://images.unsplash.com/photo-1599566150163-29194dcaad36?auto=format&fit=crop&w=600&q=80',
    category: 'Youthful / Casual',
    suitableFaceShapes: ['Round', 'Oval', 'Heart'],
    suitableHairTypes: ['Wavy', 'Curly', 'Thick'],
    mappedServiceId: 'srv-02',
  },
  {
    id: 'HS05',
    name: 'Buzz Cut with Precision Lineup',
    description: 'Ultra-clean uniform short cut accented with razor-sharp temple lines and fade.',
    imageUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&q=80',
    category: 'Minimalist',
    suitableFaceShapes: ['Diamond', 'Square', 'Oval'],
    suitableHairTypes: ['Straight', 'Curly', 'Coily'],
    mappedServiceId: 'srv-01',
  },
];

export const DEMO_STAFF: SalonStaff[] = [
  {
    id: 'stf-01',
    userId: 'usr-stf-01',
    name: 'Vikram Joshi (Master Stylist)',
    salonId: 'salon-pune-01',
    specialization: 'Fades & AI Style Precision',
    status: 'AVAILABLE',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    rating: 4.9,
  },
  {
    id: 'stf-02',
    userId: 'usr-stf-02',
    name: 'Karan Malhotra',
    salonId: 'salon-pune-01',
    specialization: 'Beard Sculpting & Scissor Work',
    status: 'BUSY',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
    rating: 4.8,
  },
  {
    id: 'stf-03',
    userId: 'usr-stf-03',
    name: 'Aanya Sen',
    salonId: 'salon-pune-01',
    specialization: 'Color, Balayage & Treatments',
    status: 'AVAILABLE',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80',
    rating: 4.9,
  },
];

export const INITIAL_DEMO_TOKEN: QueueToken = {
  tokenId: 'tok-108-demo',
  tokenNumber: 108,
  position: 4,
  estimatedWait: 24,
  status: 'WAITING',
  salonId: 'salon-pune-01',
  customerId: 'usr-customer-001',
  serviceId: 'srv-02',
  serviceName: 'Skin Fade & Textured Crop',
  servicePrice: 599,
  staffId: 'stf-01',
  staffName: 'Vikram Joshi',
  queueDate: new Date().toISOString().split('T')[0],
  createdAt: new Date().toISOString(),
  stationNumber: 3,
  selectedHairstyleId: 'HS01',
  selectedHairstyleName: 'Textured Crop',
};

export const INITIAL_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-01',
    userId: 'usr-customer-001',
    title: 'Welcome to SalonFlow AI',
    message: 'Try our AI Hairstyle consultation to find the perfect cut tailored to your face shape.',
    type: 'BOOKING_CONFIRMED',
    isRead: false,
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    actionUrl: '/ai-recommend',
  },
];

export const INITIAL_DEMO_APPOINTMENTS: Appointment[] = [
  {
    id: 'apt-108-live',
    customerId: 'usr-customer-001',
    salonId: 'salon-pune-01',
    salonName: 'SalonFlow Studio & Lounge',
    salonAddress: 'Lane 7, Koregaon Park, Pune, Maharashtra 411001',
    salonArea: 'Koregaon Park',
    serviceId: 'srv-02',
    serviceName: 'Skin Fade & Textured Crop',
    servicePrice: 599,
    serviceDuration: 35,
    staffId: 'stf-01',
    staffName: 'Vikram Joshi (Master Stylist)',
    staffAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    appointmentDate: new Date().toISOString().split('T')[0],
    appointmentTime: '04:30 PM',
    status: 'CONFIRMED',
    source: 'ONLINE',
    bookingType: 'WALK_IN',
    tokenNumber: 108,
    paymentMethod: 'Pay at Salon Counter',
    paymentStatus: 'PENDING_AT_COUNTER',
    createdAt: new Date(Date.now() - 1800000).toISOString(),
  },
  {
    id: 'apt-109-scheduled',
    customerId: 'usr-customer-001',
    salonId: 'salon-pune-02',
    salonName: 'SalonFlow Elite Barbering',
    salonAddress: 'High Street, Baner, Pune, Maharashtra 411045',
    salonArea: 'Baner',
    serviceId: 'srv-04',
    serviceName: 'The Executive Combo (Cut + Beard)',
    servicePrice: 799,
    serviceDuration: 50,
    staffId: 'stf-02',
    staffName: 'Karan Malhotra',
    staffAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
    appointmentDate: new Date(Date.now() + 86400000).toISOString().split('T')[0],
    appointmentTime: '11:30 AM',
    status: 'CONFIRMED',
    source: 'ONLINE',
    bookingType: 'SCHEDULED',
    paymentMethod: 'UPI (GPay)',
    paymentStatus: 'PAID',
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'apt-105-completed',
    customerId: 'usr-customer-001',
    salonId: 'salon-pune-04',
    salonName: 'SalonFlow Precision Grooming',
    salonAddress: 'East Avenue, Kalyani Nagar, Pune 411006',
    salonArea: 'Kalyani Nagar',
    serviceId: 'srv-01',
    serviceName: 'Precision Signature Haircut',
    servicePrice: 499,
    serviceDuration: 30,
    staffId: 'stf-01',
    staffName: 'Vikram Joshi (Master Stylist)',
    staffAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    appointmentDate: '2026-08-28',
    appointmentTime: '03:00 PM',
    status: 'COMPLETED',
    source: 'ONLINE',
    bookingType: 'WALK_IN',
    tokenNumber: 94,
    paymentMethod: 'Credit Card',
    paymentStatus: 'PAID',
    createdAt: '2026-08-28T14:00:00Z',
  },
];
